
export const dummyCHA= [
{
    name: "Mangalore",
    list: [
    {
        "destinationPort":"Singapore",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
   
    {
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },

    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
       
    },

    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
      
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },

    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
      
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
   
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },

    {
   
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    ],
},

{
    name: "Nava Shiva",
    list: [
    {
        "destinationPort":"Singapore",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
   
    {
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
   
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    ],
},
   
{
    name: "Chennai Port",
    list: [
    {
        "destinationPort":"Singapore",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
   
    {
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
        "destinationPort":"Dijibouti",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    {
   
        "destinationPort":"Jebel Ali",
        "chaCharges":"32.3",
        "silicaGelCharges":"392.4",
        "craftPaperCharges":"341.4",
        "transportCharges":"22.2",
        "customCharges":"9318.3",
        "loadingCharges":"8194.3",
        "cooCharges": "23.33",
    },
    ],
},
   
]