export const eceForm = [
  // {
  //   label: "Name",
  //   name: "name",
  //   type: "textInput",
  //   placeholder: "Fill the name",
  // },
  // {
  //   label: "Company Name",
  //   name: "companyName",
  //   type: "textInput",
  //   placeholder: "Fill the Company Name",
  // },
  // {
  //   label: "Contact Details",
  //   name: "contactDetails",
  //   type: "numInput",
  //   placeholder: "Fill the Company Details",
  // },
  // {
  //   label: "Date",
  //   name: "date",
  //   type: "date",
  //   placeholder: "Fill the date",
  // },
  // {
  //   label: "Choose One",
  //   name: "chooseOne",
  //   type: "radio",
  //   options: [{ name: "Exporter" }, { name: "Importer" }, { name: "Miller" }],
  // },
  {
    label: "Today's Dollar Price",
    name: "dollarPrice",
    type: "numInput",
    placeholder: "Enter the Dollar Price",
    step: 1,
  },
  {
    label: "Type of Booking",
    name: "bookingType",
    type: "radio",
    options: [{ name: "FCL" }],
    step: 1,
  },
  {
    label: "Terms Of Shipment",
    name: "shipmentTerms",
    placeholder: "Select Shipment Method",
    type: "select",
    options: [
      { value: " FOB", label: "FOB" },
      { value: "CIF", label: "CIF" },
    ],
    step: 1,
  },
  {
    label: "Type of Product",
    name: "productType",
    type: "select",
    placeholder: "rice",
    options: [],
    step: 2,
  },
  {
    label: "Rice Category",
    name: "productCategory",
    type: "select",
    placeholder: "Select Rice Category",
    options: [],
    step: 2,
  },
  {
    label: "Rice Variety",
    name: "variety",
    type: "select",
    placeholder: "Select Rice Variety",
    options: [],
    step: 2,
  },

  {
    label: "Sourcing Location",
    name: "sourcingLocation",
    type: "select",
    placeholder: "Select Sourcing Location",
    options: [],
    step: 3,
  },
  {
    label: "Destination Port / City",
    name: "destinationPort",
    type: "select",
    placeholder: "Search Here",
    options: [],
    step: 4,
  },
  {
    label: "Origin Port / City",
    name: "originPort",
    type: "select",
    placeholder: "Search Here",
    options: [],
    step: 5,
  },
  {
    label: "Broken Percentage(%)",
    name: "brokenPercentage",
    type: "counter",
    placeholder: "@5",
    step: 6,
  },

  {
    label: "Enter your own ex-mill price",
    name: "exMill",
    type: "numInput",
    placeholder: "write down ex-mill price",
    step: 7,
  },

  {
    label: "Type of Container",
    name: "containerType",
    type: "select",
    placeholder: "Select type of container",
    options: [{ value: "20ft", label: "General Container(20ft)" }],
    step: 8,
  },
  {
    label: "Container Count",
    name: "containerCount",
    type: "counter",
    placeholder: "@1",
    step: 8,
  },
  {
    label: "Container Weight ",
    name: "containerWeight",
    type: "radio",
    options: [{ name: "Metric tons" }, { name: "Kg" }, { name: "Quintal" }],
    step: 8,
  },
  {
    label: "Type of Bags ",
    name: "bagTypes",
    type: "select",
    placeholder: "Eg. BOPP",
    options: [],
    step: 9,
  },
  {
    label: "Bag Weight",
    name: "bagWeight",
    type: "select",
    placeholder: "Bag weight in kg ",
    options: [],
    step: 9,
  },
  {
    label: "Bags Charges",
    name: "bagsCharges",
    type: "numInput",
    placeholder: "Fill the Bags charges:",
    step: 9,
  },
  {
    label: "Transportation Charges(Rs/mt ton)",
    name: "TransportationCharges",
    type: "numInput",
    placeholder: "Fill the Transport charges:",
    step: 10,
  },

  {
    label: "CFS Handling Charges(Rs/mt ton)",
    name: "CfshandlingCharges",
    type: "numInput",
    placeholder: "Fill the handling charges:",
    step: 10,
  },
  // {label:"Craft Paper" ,name:"CraftPaper" , type:"input"},
  // {label:"Silica Gel" ,name:"SilicaGel" , type:"input"},
  // {label:"Loading Charges" ,name:"LoadingCharges" , type:"input"},
  // {label:"Transportation Charges" ,name:"TransportationCharges" , type:"input"},
  // {label:"Custom Charges" ,name:"CustomCharges" , type:"input"},
  // {label:"PQ Certificate" ,name:"PQCertificate" , type:"input"},
  // {label:"COO" ,name:"COO" , type:"input"},
  {
    label: "Finance Cost (Rs/mt ton)",
    name: "FinanceCost",
    type: "numInput",
    placeholder: "Fill the finance costing:",
    step: 10,
  },
  {
    label: "Inspection Cost (Rs/mt ton)",
    name: "InspectionCost",
    type: "numInput",
    placeholder: "Fill the Inspection cost:",
    step: 11,
  },
  {
    label: "Overheads (Rs/mt ton)",
    name: "Overheads",
    type: "numInput",
    placeholder: "Overheads:",
    step: 11,
  },
  {
    label: "Shipping Line Local Charges (Rs/mt ton)",
    name: "ShippingCost",
    type: "numInput",
    placeholder: "Fill the Shipping Line Charges:",
    step: 12,
  },

  {
    label: "Original B/L Fee",
    name: "OriginalBLFee",
    type: "numInput",
    placeholder: "Original B/L Fee",
    step: 12,
  },

  {
    label: "Insurance Cost (Rs/mt ton)",
    name: "InsuranceCost",
    type: "numInput",
    placeholder: "Fill the Insurance cost:",
    step: 13,
  },
  {
    label: "Margin (Rs/mt ton)",
    name: "MarginCost",
    type: "numInput",
    placeholder: "Fill the margin cost:",
    step: 13,
  },
  {
    label: "20% Export Duty",
    name: "20% Export Duty",
    type: "checkbox",
    step: 13,
  },
  // {
  //   label: "OFC(Ocean Freight Charges) (Rs/mt ton)",
  //   name: "Ofc",
  //   type: "numInput",
  //   id: "hideInput",
  //   placeholder: "Fill the OFC Charges:",
  // },
];
