export const NavbarOptions = [
  {
    option: "Dashboard",
    navigateTo: "/admin/dashboard",
    icon: "dashboard",
    color: "blue",
    badge: "",
  },
  {
    option: "Products",
    navigateTo: "/admin/dashboard/export-costing",
    icon: "disc",
    color: "teal",
    badge: "",
  },
  // {
  //   option: "Location",
  //   navigateTo: "/admin/dashboard/locations",
  //   icon: "dollar",
  //   color: "green",
  // },
  // {
  //   option: "Packaging",
  //   navigateTo: "/admin/dashboard/managePackaging",
  //   icon: "calendar",
  //   color: "yellow",
  //   badge: "",
  // },
  // {
  //   option: "CHA",
  //   navigateTo: "/admin/dashboard/cha",
  //   icon: "dice",
  //   color: "red",
  //   badge: "",
  // },
  // {
  //   option: "SHL",
  //   navigateTo: "/admin/dashboard/shl",
  //   icon: "heart",
  //   color: "yellow",
  //   badge: "",
  // },
  // {
  //   option: "OFC",
  //   navigateTo: "/admin/dashboard/ofc",
  //   icon: "star",
  //   color: "blue",
  //   badge: "",
  // },
  // {
  //   option: "Transportation",
  //   navigateTo: "/admin/dashboard/transport",
  //   icon: "disc",
  //   color: "green",
  //   badge: "",
  // },
  // {
  //   option: "PWIP Services",
  //   navigateTo: "/admin/dashboard/pwipServices",
  //   icon: "calendar",
  //   color: "yellow",
  //   badge: "",
  // },
  // {
  //   option: "Others",
  //   navigateTo: "/admin/dashboard/others",
  //   icon: "calendar",
  //   color: "yellow",
  //   badge: "",
  // },
];
